id: P004326
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17437
  title: ཁོར་ཡུག་དང་ཐོན་ཁུངས་སྲུང་སྐྱོང་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    0f13e183f56a40d68099952cdf43097b:
      image_group_id: I4PD3068
      title: ''
      volume_number: 1
      total_pages: 330
